---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: nginx-deployment
 namespace: reddy
 labels:
  app: nginxapp
spec:
 replicas: 3
 selector:
  matchLabels:
   app: nginxapp
 template:
  metadata:
   name: nginx-pod
   labels:
    app: nginxapp
  spec:
   containers:
    - name: mynginx
      image: nginx:1.9.1
      ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: service1
 namespace: reddy
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
 selector:
  app: nginxapp
...
