---
apiVersion: v1
kind: ReplicationController
metadata:
 name: jenkinsrc
 namespace: reddy
spec:
 replicas: 1
 selector:
  app: jenkinsapp       
 template:
  metadata:
   name: myjenkins
   namespace: reddy
   labels:
    app: jenkinsapp
  spec:
   containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
      - containerPort: 8080
...
