---
apiVersion: v1
kind: Pod
metadata:
 name: myjenkins
 namespace: reddy
 labels:
  app: jenkinsapp
spec:
 containers:
  - name: myjenkins
    image: jenkins/jenkins
    ports:
     - containerPort: 8080
...
