---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: jenkinsrs
 namespace: reddy
spec:
 replicas: 1
 selector: 
  matchLabels:
   app: jenkinsapp
 template:
  metadata:
   name: myjenkins
   namespace: reddy
   labels:
    app: jenkinsapp
  spec:
   containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
      - containerPort: 8080
...
