---
apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: tomcatds
spec:
 template:
  metadata:
   labels:
    app: tomcat       
  spec:
   containers:
    - name: tomcatcontainer
      image: tomcat
      ports:
       - containerPort: 8080
 selector:
  matchLabels:
   app: tomcat         
---
apiVersion: v1
kind: Service
metadata: 
 name: service-tomcat
spec:
 type: NodePort
 selector:
  app: tomcat
 ports:
  - port: 8080
    targetPort: 8080
...    
