---
apiVersion: v1
kind: Pod
metadata: 
 name: tomcatpod
 namespace: reddy
 labels:
  app: tomcatapp
spec:
 containers:
  - name: mytomcat
    image: tomcat
    ports:
     - containerPort: 8080  
...
