---
apiVersion: v1
kind: ReplicationController
metadata:
 name: tomcatrc
 namespace: reddy
spec:
 replicas: 3
 template:
  metadata:
   name: tomcatpod
   namespace: reddy
   labels:
    app: tomcatapp
  spec:
   containers:
    - name: mytomcat
      image: tomcat
      ports:
       - containerPort: 8080
...
